#pragma once

#include <cstdint>
#include <deque>
#include <functional>
#include <future>
#include <mutex>
#include <vector>
#include "rust/cxx.h"

class DaemonContext; // forward declaration; full type in net-policy.h

namespace grpc_bridge {

/*One item per inbound Rust-originated control RPC. Allocated on the calling
 *(Rust/tokio blocking) thread's stack, pushed onto the queue by pointer, and
 *run only by the epoll thread (via DispatchGrpcRustQueueEvent in
 *net-policy.cpp) until `done` is fulfilled -- there is never more than one
 *writer to a given item's fields at a time, which is what lets this cross a
 *thread boundary with no lock of its own.*/
struct GrpcDispatchItem {
  std::function<void()> work;
  std::promise<void> done;
};

/*Thread-safe multi-producer/single-consumer queue: any number of tokio
 *blocking threads call Push(); exactly one consumer (the epoll loop, woken
 *via the eventfd passed at construction) calls DrainAll().*/
class GrpcDispatchQueue {
public:
  explicit GrpcDispatchQueue(int wake_fd);

  void Push(GrpcDispatchItem* item);        // calling (tokio blocking) thread
  std::vector<GrpcDispatchItem*> DrainAll(); // epoll thread only

private:
  int wake_fd_;
  std::mutex mutex_;
  std::deque<GrpcDispatchItem*> queue_;
};

// Rust-callable dispatch functions. Each builds a closure capturing `daemon`
// by pointer, pushes it onto `queue`, blocks until the epoll thread
// (DispatchGrpcRustQueueEvent, net-policy.cpp) has run it, and returns the
// typed result. Implemented in net-policy.cpp, where DaemonContext's full
// definition and the legacy policy functions are already visible.
int32_t GrpcDispatchResetConfig(DaemonContext* daemon, GrpcDispatchQueue* queue);

int32_t GrpcDispatchPodUp(DaemonContext* daemon, GrpcDispatchQueue* queue, int32_t epoll_fd,
                           int32_t pid, uint64_t pod_id);

int32_t GrpcDispatchPodDown(DaemonContext* daemon, GrpcDispatchQueue* queue, int32_t epoll_fd,
                             uint64_t pod_id);

int32_t GrpcDispatchDeletePolicyRule(DaemonContext* daemon, GrpcDispatchQueue* queue,
                                      rust::Str policy_name);

int32_t GrpcDispatchDumpHeapProfile(DaemonContext* daemon, GrpcDispatchQueue* queue,
                                    bool enable);

// Full definition generated by cxx bridge codegen (from the shared `struct
// DumpConnectionsResult` declared in crates/net_policy_control/src/lib.rs's
// bridge module) in net_policy_control_cxxbridge/lib.h -- items there is
// rust::Vec<rust::String>, not std::vector<std::string>. Only forward-declared
// here so this header's function declaration is self-contained; net-policy.cpp
// sees the complete type via its earlier #include of that generated header.
struct DumpConnectionsResult;

DumpConnectionsResult GrpcDispatchDumpConnections(DaemonContext* daemon, GrpcDispatchQueue* queue,
                                                    int32_t limit);

int32_t GrpcDispatchUpdateNodeConfig(DaemonContext* daemon, GrpcDispatchQueue* queue,
                                      bool is_delete, rust::Vec<rust::String> node_ips);

int32_t GrpcDispatchSetLogLevel(DaemonContext* daemon, GrpcDispatchQueue* queue, int32_t level);

// Full definitions generated by cxx bridge codegen (from the shared structs
// declared in crates/net_policy_control/src/lib.rs's bridge module) in
// net_policy_control_cxxbridge/lib.h -- fields there are rust::String /
// rust::Vec<T>, not std::string / std::vector<T>. Only forward-declared here
// so this header's function declaration is self-contained; net-policy.cpp
// sees the complete types via its earlier #include of that generated header.
struct PolicyRuleConfigEntry;
struct ContainerInfo;
struct DumpConfigResult;

DumpConfigResult GrpcDispatchDumpConfig(DaemonContext* daemon, GrpcDispatchQueue* queue,
                                          rust::Str policy_name);

// Full definitions generated by cxx bridge codegen (from the shared structs
// declared in crates/net_policy_control/src/lib.rs's bridge module) in
// net_policy_control_cxxbridge/lib.h -- nested vector fields there are
// rust::Vec<T>, not std::vector<T>. Only forward-declared here so this
// header's function declaration is self-contained; net-policy.cpp sees the
// complete types via its earlier #include of that generated header.
struct HttpMatchRule;
struct AddressEndpoint;
struct PortRange;
struct PolicyRuleSpec;

int32_t GrpcDispatchAddPolicyRule(DaemonContext* daemon, GrpcDispatchQueue* queue,
                                    rust::Str policy_name, rust::Vec<PolicyRuleSpec> rules);

// Epoll callback (RcvCbFunc-shaped: int32_t(int32_t epoll_fd, int32_t fd,
// void* ptr)) for the Rust dispatch queue's wake eventfd. Drains `queue`
// (read from the registering RcvEpollCb, threaded through via `ptr`) and
// runs each item's closure on this (the epoll) thread. Implemented in
// net-policy.cpp since it needs RcvEpollCb's shape from net-policy.h.
int32_t DispatchGrpcRustQueueEvent(int32_t epoll_fd, int32_t fd, void* ptr);

} // namespace grpc_bridge
